### ISSUE TITLE
The description of the ".trim" is written in the description of the ".number"

### ISSUE THREAD

**Issue by GyeongTae0319** [vuejs-kr/docs-next#152]
[폼 입력 바인딩 > 수식어](https://v3.ko.vuejs.org/guide/forms.html#trim) `.trim` 의 설명에 `.number` 의 설명이 적혀있습니다.

Original: [Form Input Bindings > Modifiers](https://v3.vuejs.org/guide/forms.html#trim)

![image](https://user-images.githubusercontent.com/40243194/119006337-414d0b80-b9cb-11eb-9e8d-2384feb768f7.png)

**Comment by narusas** [comment]
확인해보고 반영하겠습니다. 
알려주셔서 감사합니다 ^^

**Comment by narusas** [comment]
trim 부분 번역 수정 되었습니다
