### ISSUE TITLE
기술적 오류가 있는 번역

### ISSUE THREAD

**Issue by niceplugin** [vuejs-kr/docs-next#176]
[main 브런치]/ko-KR/src/guide/essentials/list.md

문서의 # key를 통한 상태유지, 첫 번재 문단의 두 번째 문장

> Vue는 데이터 항목의 순서가 변경된 경우 항목의 순서와 일치하도록 DOM 앨리먼트를 이동하는 대신(Reflow를 유발하는 대신)

에서 `(Reflow를 유발하는 대신)`은 기술적으로 잘못된 부연설명이므로 삭제되어야 하는 내용입니다.

브라우저 렌더링 절차는 `렌더 트리 (재)구성 > (리)플로우 > (리)페인트`이고,
**DOM 엘리먼트를 이동하면 브라우저는 렌더트리를 재구성**합니다.

뷰는 이동이 필요한 엘리먼트를 이동하지 않고 내부 컨텐츠만 교체해 이러한 비용을 줄이려고 하는 것이고,
따라서 내부 컨텐츠의 텍스트 노드들만 수정될 경우, 뷰의 설계 의도대로 브라우저는 `리플로우 > 리페인트`만 진행합니다.

부연설명이 있는 해석의 의도는 좋았으나,
"렌더트리 재구성 단계를 줄여 최적화 했다"를 "리플로우 단계를 줄여 최적화 했다"라고 기술적으로 잘못된 내용을 전달하므로
해당 부분은 삭제되어야 합니다.

**Comment by narusas** [comment]
ㅇㅇ 
이 내용을 더 추가하는게 좋지 않을까요?

**Comment by niceplugin** [comment]
프로젝트 투두리스트에 넣으려 했는데 생성이 안되서 다시 열어둡니다.
지금은 다들 바쁘신듯 하니
추후 전체적으로 가이드 문서 검토단계에서 넣으면 좋을듯 합니다.

**Comment by narusas** [comment]
(역자주: DOM Node의 위치가 변경되면 DOM Tree구조가 변경 되었기 때문에 Render Tree를 재구성한후에, 재 구성된 Node들의 위치,크기,깊이등을 다시 계산하는 Reflow 과정을 수행하고, DOM Node를 다시 그려 내는 Repaint 과정을 거치게 됩니다. 만약 Node를 이동하지 않고, Node 내부의 컨텐츠만 변경한다면 렌더 트리 재구성이나, Reflow를 수행하지 않고, 해당 Node만 Repaint 하면 되기 때문에 효율적입니다. )

역자주로 이정도의 내용으로 넣을려고 힙니다

**Comment by narusas** [comment]
아무튼 reflow가 필요한지 repaint만으로 충분하지를 브라우저가 판단하는데 최신 브라우저들이 적극적으로 repaint만으로 때울려고 하는 경향이 있긴 합니다. 정확히는 GPU상의 레이어에 올려두고 그 레이어만 다시 그려내는 방식으로 성능을 달성하려는..

**Comment by narusas** [comment]
그래서 가끔 브라우저 화면이 깨지는 경우로 발생하기는 합니다. 크롬에서 테스트  옵션 키고  쓰면 종종 볼수 있습니다 ^^

**Comment by niceplugin** [comment]
네. 그럼 이 건은 닫도록 하겠습니다.
